server:
  port: 8081

spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string: 192.168.182.130:2181
      time-out: 50000
      service-registry-path: /services
      
      


